Repository luxonis/depthai-shared, pull requests merged in 2021-06, with the labels that each got.

#28 IMU: BNO 085/6 support
  include/depthai-shared/common/Timestamp.hpp
  include/depthai-shared/datatype/DatatypeEnum.hpp
  include/depthai-shared/datatype/RawIMUData.hpp
  include/depthai-shared/properties/IMUProperties.hpp
  src/datatype/DatatypeEnum.cpp
Labels: Gen2

#37 Release v2.5.0
  .gitignore
  include/depthai-shared/common/CameraBoardSocket.hpp
  include/depthai-shared/common/CameraInfo.hpp
  include/depthai-shared/common/CameraModel.hpp
  include/depthai-shared/common/ChipTemperature.hpp
  include/depthai-shared/common/CpuUsage.hpp
  include/depthai-shared/common/EepromData.hpp
  include/depthai-shared/common/Extrinsics.hpp
  include/depthai-shared/common/RotatedRect.hpp
  include/depthai-shared/common/Size2f.hpp
  include/depthai-shared/common/StereoRectification.hpp
  include/depthai-shared/common/Timestamp.hpp
  include/depthai-shared/common/UsbSpeed.hpp
  include/depthai-shared/datatype/DatatypeEnum.hpp
  include/depthai-shared/datatype/RawBuffer.hpp
  include/depthai-shared/datatype/RawCameraControl.hpp
  include/depthai-shared/datatype/RawIMUData.hpp
  include/depthai-shared/datatype/RawImageManipConfig.hpp
  include/depthai-shared/datatype/RawImgDetections.hpp
  include/depthai-shared/datatype/RawImgFrame.hpp
  include/depthai-shared/datatype/RawNNData.hpp
  include/depthai-shared/datatype/RawSpatialImgDetections.hpp
  include/depthai-shared/datatype/RawSpatialLocationCalculatorConfig.hpp
  include/depthai-shared/datatype/RawSpatialLocations.hpp
  include/depthai-shared/datatype/RawTracklets.hpp
  include/depthai-shared/pipeline/NodeIoInfo.hpp
  include/depthai-shared/pipeline/NodeObjInfo.hpp
  include/depthai-shared/properties/ColorCameraProperties.hpp
  include/depthai-shared/properties/DetectionNetworkProperties.hpp
  include/depthai-shared/properties/GlobalProperties.hpp
  include/depthai-shared/properties/IMUProperties.hpp
  include/depthai-shared/properties/ImageManipProperties.hpp
  include/depthai-shared/properties/MonoCameraProperties.hpp
  include/depthai-shared/properties/NeuralNetworkProperties.hpp
  include/depthai-shared/properties/ObjectTrackerProperties.hpp
  include/depthai-shared/properties/SPIOutProperties.hpp
  include/depthai-shared/properties/SpatialDetectionNetworkProperties.hpp
  include/depthai-shared/properties/SpatialLocationCalculatorProperties.hpp
  include/depthai-shared/properties/StereoDepthProperties.hpp
  include/depthai-shared/properties/SystemLoggerProperties.hpp
  include/depthai-shared/properties/VideoEncoderProperties.hpp
  include/depthai-shared/properties/XLinkInProperties.hpp
  include/depthai-shared/properties/XLinkOutProperties.hpp
  src/datatype/DatatypeEnum.cpp
Labels: 2021, Gen2, release

#36 StereoDepth: mesh rectification, depth configurable resolution
  include/depthai-shared/properties/StereoDepthProperties.hpp
Labels: Gen2, enhancement
